version: "3.7"

services:
  pminio:
    image: minio/minio
    environment:
      - "MINIO_ACCESS_KEY={S3_ACCESS_KEY}"
      - "MINIO_SECRET_KEY={S3_SECRET_KEY}"
    ports:
      - "{MINIO_PORT}:9000"
      - "{MINIO_CONSOLE_PORT}:9090"
    volumes:
      - "oci_pminio:/data"
    depends_on:
      - pulp
    command: "server /data --console-address ':9090'"

volumes:
  oci_pminio:
    name: "{COMPOSE_PROJECT_NAME}_pminio"
